baseURL = "https://driftlessit.org/"
title = "Driftless IT Community"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Driftless IT Community" # title for frontpage, may include image
copyright = "Patrick Palmersheim"
description = 'IT community located in <br />NE Iowa, SW Wisconsin and SE Minnesota <br /> open to all IT professionals'
startbuttonText = "Forum"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = false
title = 'Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep donec'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = false

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'What is this community&#63;'
body = '''
A couple guys got together one day and asked each other "what do you think about a place that IT folk can get help from others
in the local area?" The idea sounded great, and this place was born.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Contacts"
body = "Right now the best contact for this community is the Github repo, until the forum can be created."

[[params.three.feature]]
icon = "fa-code"
title = "This site"
body = "This site is created with Hugo. The code is hosted on Github, and the webserver is Cloudflare Pages."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Support"
body = "There may be a need to have some monetary support for this community as it becomes bigger. Right now, donations are not needed"

[[params.three.feature]]
icon = "fa-flag-o"
title = "What&#39;s coming"
body = "A forum, possibly a matrix server, maybe a knowledge base. Anything is possible"

[params.cta]
enable = true
title = "Contribute on Github"
body = "If you would like to contribute to this site, or reach out to the maintainer go to the Github page."

[[params.cta.link]]
href = "https://github.com/slinkytoad/driftlessit"
text = "Github"
special = true

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
